### ISSUE TITLE
About the performance of the teacher model (i.e. ,Self-supervised Teacher Training)

### ISSUE THREAD

**Issue by jzhu-tju** [megvii-research/KD-MVS#1]
Amazing Work!
After reading your paper, I have a little question. Table 5 shows the performance of your self-supervised teacher training when 
using MVSNet as the backbone, would you like to tell me the performance on DTU using CasMVSNet when only carrying out the self-supervised teacher training. 
Thanks, looking forward for your kind reply!

**Comment by DingYikang** [comment]
Hi, thank you for your interest in our work. 
Actually, the reported results in Tab.5 are obtained by applying self-supervised teacher training on CasMVSNet (not on MVSNet). Hope this can help you.

**Comment by jzhu-tju** [comment]
Thanks for your reply!
As shown in U-MVS(ICCV 2021), the performance when only applying the photometric loss on CasMVSNet is 0.4041 and when I reproduce in the same setting, the performance is even higer (about 0.39).
In your paper, the  performance obtained by only applying the photometric loss on CasMVSNet is 0.495, which is much different with the above.

Is there any difference in experimental settings?
Looking forward to your reply.
Many thanks!

**Comment by DingYikang** [comment]
Hi, thank you for your feedback. 
In our experiments, we didn't follow the settings of U-MVS, so the results may look different. Several factors may affect the final results (e.g., fusion method, fusion threshold, etc). In the ablation experiments in Tab.5, we guarantee the settings are fair to illustrate the effectiveness of different featuremetric loss.
Hope this can help you.

**Comment by jzhu-tju** [comment]
Sincerely Thanks!
