### ISSUE TITLE
A problem while reproducing the result on DTU

### ISSUE THREAD

**Issue by weetrain** [megvii-research/KD-MVS#2]
Great job!
I downloaded the pretrained model, and executed the test(both normal and gipuma) and MATLAB evaluation，finally got the overall 0.3397(normal,0.3409 for gipuma),which is 0.327 in your paper. I wonder if there is something wrong about my impletment. I would appreciate it if you can offer some guidance.

**Comment by DingYikang** [comment]
Hi, thanks for your feedback.
To reproduce the results, it's better to make sure that you use the latest code and configuration, use the right ckpt 'model_kd_dtu.ckpt', as well as the right environment, for example, the different version of python and pytorch could have an impact on the final results.
Hope this can help you.

**Comment by DingYikang** [comment]
> Great job! I downloaded the pretrained model, and executed the test(both normal and gipuma) and MATLAB evaluation，finally got the overall 0.3397(normal,0.3409 for gipuma),which is 0.327 in your paper. I wonder if there is something wrong about my impletment. I would appreciate it if you can offer some guidance.

Hi, I re-test our pretrained models, and the result looks OK. I'm wondering did you use the MATLAB code in TransMVSNet? The initial version in TransMVSNet has some debug codes, which would affect the final score. You can download the new version and try it again.
If you still meet any problems, feel free to contact me ([dyk20@mails.tsinghua.edu.cn](mailto:dyk20@mails.tsinghua.edu.cn)), I'll help you solve the problems.
